var mappings = {
  1: "person",
  3: "car",
  7: "train",
  5: "airplane",
  6: "bus",
  16: "bird",
  17: "cat",
  18: "dog",
  19: "horse",
  63: "couch",
  "-1": "NONE_OF_THE_ABOVE",
  "airplane": 5,
  "bird": 16,
  "bus": 6,
  "car": 3,
  "cat": 17,
  "couch": 63,
  "dog": 18,
  "horse": 19,
  "person": 1,
  "train": 7,
  "NONE_OF_THE_ABOVE": -1
};